modLoader="javafml"
loaderVersion = "[${forge_version},)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors = "QiuYe"
description = "${mod_description}"
displayURL = "${mod_url}"
credits = ""

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "ldlib"
mandatory = true
embedded = true
versionRange = "[${ldlib_version},)"
ordering = "AFTER"
side = "BOTH"
[dependencies.${ mod_id }.mc-publish]
ignore = false
modrinth = "ldlib"
curseforge = "ldlib"

[[dependencies.${ mod_id }]]
modId = "configuration"
mandatory = true
embedded = true
versionRange = "[${configuration_version},)"
ordering = "AFTER"
side = "BOTH"
[dependencies.${ mod_id }.mc-publish]
ignore = false
modrinth = "configuration"
curseforge = "configuration"


[[dependencies.${mod_id}]]
modId = "gtceu"
mandatory = false
versionRange = "[7,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "jei"
mandatory = false
versionRange = "[${jei_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "emi"
mandatory = false
versionRange = "[${emi_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "jade"
mandatory = false
versionRange = "[${jade_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ad_astra"
mandatory = false
versionRange = "[1,)"
ordering = "AFTER"
side = "BOTH"